#!/usr/bin/env bash

role=${CONTAINER_ROLE:-app}

set -e

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ "$role" = "app" ]; then
    if [ $# -gt 0 ]; then
        exec gosu $WWWUSER "$@"
    else
        exec php-fpm
    fi
elif [ "$role" = "schedule" ]; then
    while [ $(date +%S) != '00' ]
    do
        echo $(date +%S)
        sleep 1
    done
    while [ true ]
    do
        gosu $WWWUSER php /var/www/html/artisan schedule:run --verbose --no-interaction & sleep 60
    done
elif [ "$role" = "queue" ]; then
    echo "Running the queue..."
    gosu $WWWUSER php /var/www/html/artisan horizon
fi
