- name: 'Add docker host'
  hosts: localhost
  tasks:
      # Gather facts
      - name: 'Include global vars'
        include_vars:
            dir: ./../../vars/global
      - name: 'Get container status'
        docker_container_info:
            name: "{{ SHORT_PROJECT_NAME }}_backend_app_1"
        register: status
      - add_host:
            env: "{{ env }}"
            hostname: "backend_app"
            ansible_connection: "docker"
            ansible_host: "{{ SHORT_PROJECT_NAME }}{{ (status.exists)|ternary('_', '-') }}backend_app{{ (status.exists)|ternary('_', '-') }}1"
            ansible_python_interpreter: "/usr/bin/python3"
- name: 'Connect to docker backend_app and run composer install'
  hosts: backend_app
  remote_user: sail
  gather_facts: no
  tasks:
    # Gather facts
    - name: 'Include global vars'
      include_vars:
          dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
          dir: ./../../vars/{{ env }}
    - name: 'Run command'
      when:
        - env == "local"
      raw: "composer install"
    - name: 'Run command'
      when:
        - env != "local"
      raw: "composer install -q --no-ansi --no-interaction --no-progress --prefer-dist --no-scripts"
