APP_ENV: staging
APP_DEBUG: true
DEBUGBAR_ENABLED: false
FORCE_MAIL_SETTING: true
APP_URL: 'http://snmeble.dev.lovata.tech'
BROADCAST_DRIVER: log
CACHE_DRIVER: file
QUEUE_CONNECTION: sync
SESSION_DRIVER: file

RESTART_POLICY: "no"

ENABLE_REDIS: false
ENABLE_QUEUE: false
ENABLE_MAILPIT: true

SAIL_XDEBUG_MODE: off

APP_CODE_PATH_CONTAINER: /var/www/html/snmeble.pl/app
